### ISSUE TITLE
too many arguments to resolve()

### ISSUE THREAD

**Issue by thatbudakguy** [ucldc/potto-loris#3]
after some modifications to the beanstalk environment to get this running in python2.7, I can start the environment and view the `potto-loris status okay` message at /.

however, requesting an image using the iiif url format, or `info.json`, throws a `TypeError`:
```python
mod_wsgi (pid=8156): Exception occurred processing WSGI script '/opt/python/current/app/loris2.wsgi.py'.
Traceback (most recent call last):
  File "/opt/python/bundle/7/app/loris/loris/webapp.py", line 445, in __call__
 return self.wsgi_app(environ, start_response)
  File "/opt/python/bundle/7/app/loris/loris/webapp.py", line 388, in wsgi_app
 response = self.route(request)
  File "/opt/python/current/app/loris2.wsgi.py", line 132, in new_route
 return stock_route(request)
  File "/opt/python/bundle/7/app/loris/loris/webapp.py", line 427, in route
 return self.get_info(request, ident, base_uri)
  File "/opt/python/current/app/loris2.wsgi.py", line 137, in wrapped_get_info
 r = unwrapped_get_info(request, ident, base_uri)
  File "/opt/python/bundle/7/app/loris/loris/webapp.py", line 468, in get_info
 info, last_mod = self._get_info(ident,request,base_uri)
  File "/opt/python/bundle/7/app/loris/loris/webapp.py", line 529, in _get_info
 info = self.resolver.resolve(self, ident, base_uri)
TypeError: resolve() takes exactly 2 arguments (4 given)
```

**Comment by thatbudakguy** [comment]
think I can get around this by changing the function signature of `resolve()` in `s3resolver.py` to:
```python
def resolve(self, loris, ident, base_uri):
```

**Comment by tingletech** [comment]
sorry, I'm just noticing this now.

This does not pin to the loris version very well, since this was just building off of their default branch from the time I worked on it.  The underlying loris probably changed in the meanwhile.

FWIW, I'm working on migrating to python3 right now
